version: "3.8"
services:
    db:
        image: cyebukayire/client:lastest
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3306:3306"
    web:
      image: cyebukayire/server:latest
      tty: true
      stdin_open: true
      build:
          context: frontend
          dockerfile: Dockerfile
      ports:
            - "80:3000"
    nginx:
      image: cyebukayire/nginx:latest
      build:
          context:  ngnix
          dockerfile: Dockerfile
      ports:
            - "80:80"