   
version: '3.8'

services:
  server:
    image: cyebukayire/server:latest
    build:
      context: Server
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
  client:
    image: cyebukayire/client:latest 
    build: 
      context: client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile 
    image: cyebukayire/nginx:latest
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"